name: df_inv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - mlflow
  - fastapi
  - uvicorn
  - streamlit
  - pyyaml
  - pip:
      - azureml-sdk
